[package]
name = "wea-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["json"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
